### PR TITLE
Problem when used with WP integration

### PR DESCRIPTION
**Pull request by arioch1984**
I found a problem with your great Q2A theme when Q2A is used with WP integration, user-loggedin-drop-down.php will fail because execute a mysql query on qa_users table, but it not exists for WP integration.
So I excluded some features and all works fine.
Below my commit message:
- added gitignore for PHPStorm IDE
- Bug fix: user-loggedin-drop-down.php will fail if Q2A is used with Wordpress integration, now fixed excluding some login features

### CODE REVIEW

**Comment by amiyasahu** [comment]
@arioch1984 , thank you for the pull request . I will check on it soon and merge

**Comment by amiyasahu** [comment]
@arioch1984 , it is difficult to see whats got changed if you completely reformat the code . Can you please send pull request only the changed part to the dev branch so that it will become easy to merge without conflicts .

**Comment by arioch1984** [comment]
Hi @amiyasahu!
Thank's for your quickly reply!
I just found another problem with WP integration, I will fix it and then commit all.
You see all file changed only because my IDE had reformatted the code for make it compliant to standards.
I will try to commit only the changes at this time and I will try to revert previuos changes and then recommit only changed parts.

**Comment by amiyasahu** [comment]
@arioch1984 , Sure thank you . 

Please revert the formatting and send a PR to the dev branch which would be much helpful . 
No worries , In next release I will reformat the code .

**Comment by arioch1984** [comment]
ok, I had reverted and rewrite all in dev channel.
I will close this PR and open another one to dev.

**Comment by amiyasahu** [comment]
sure , thank you . I will check that soon and merge

**Pull request closed without merging**
